version: "3.6"

services:
  worker-import:
    image: ${IMAGE_VERSION}
    networks:
      - code-overlay
    extra_hosts:
      - "konsolidasi:10.104.0.2"
    # ports:
    #   - "6021:6021"
    #   - "6024:6024"
    env_file:
      - ./development.env
    volumes:
      - /mnt/konsolidasi:/data
    deploy:
      replicas: 1
      # resources:
      #   limits: 
      #     cpus: '0.4'
      #     memory: 256m
      #   reservations:
      #     cpus: '0.2'
      #     memory: 128m
      restart_policy: 
        condition: on-failure

networks:
  code-overlay:
    external: true
# volumes:
#   data:
