version: "3.6"

services:
  worker-consolidation:
    image: ${IMAGE_VERSION}
    networks:
      - code-overlay
    extra_hosts:
      - "konsolidasi:10.104.0.2"
    env_file:
      - ./development.env
    volumes:
      - /mnt/konsolidasi:/data
    deploy:
      replicas: 1
      # resources:
      #   limits: 
      #     cpus: '0.4'
      #     memory: 256m
      #   reservations:
      #     cpus: '0.2'
      #     memory: 128m
      restart_policy: 
        condition: on-failure
    secrets:
     - mcash-finance-console-worker-consolidation-dev.gpg

networks:
  code-overlay:
    external: true
secrets:
  mcash-finance-console-worker-consolidation-dev.gpg:
    external: true
